---
title: "lab10-jacob-yeung"
author: "Jacob Yeung"
date: "April 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
box1 = c(rep("blue", 2), "red")
box2 = c(rep("blue", 2), rep("red", 3), "white")

drawn_balls = matrix(nrow = 1000, ncol = 4)

for(x in 1:1000){
  y = runif(1)
  if(y > 0.5){
    drawn_balls[x, ] = sample(box1, size = 4, replace = TRUE)
  } else{
    drawn_balls[x, ] = sample(box2, size = 4)
  }
}
drawn_balls[seq(1, 5, 1), ]
freq_balls = apply(drawn_balls, MARGIN = 1, function(x) length(which(x == "blue")))
rel_freq = table(freq_balls) / 1000
rel_freq

rel_freq_series = matrix(data = 0, nrow = 1000, ncol = 5)
for(i in 2:1000){
  if(freq_balls[i] == 0){
    rel_freq_series[i, 1] = (1 + (i - 1) * rel_freq_series[i - 1, 1]) / i
    rel_freq_series[i, 2] = (i - 1) * (rel_freq_series[i - 1, 2]) / i
    rel_freq_series[i, 3] = (i - 1) * (rel_freq_series[i - 1, 3]) / i
    rel_freq_series[i, 4] = (i - 1) * (rel_freq_series[i - 1, 4]) / i
    rel_freq_series[i, 5] = (i - 1) * (rel_freq_series[i - 1, 5]) / i
  } else if(freq_balls[i] == 1){
    rel_freq_series[i, 2] = (1 + (i - 1) * (rel_freq_series[i - 1, 2])) / i
    rel_freq_series[i, 1] = (i - 1) * (rel_freq_series[i - 1, 1]) / i
    rel_freq_series[i, 3] = (i - 1) * (rel_freq_series[i - 1, 3]) / i
    rel_freq_series[i, 4] = (i - 1) * (rel_freq_series[i - 1, 4]) / i
    rel_freq_series[i, 5] = (i - 1) * (rel_freq_series[i - 1, 5]) / i
  } else if(freq_balls[i] == 2){
    rel_freq_series[i, 3] = (1 + (i - 1) * (rel_freq_series[i - 1, 3])) / i
    rel_freq_series[i, 2] = (i - 1) * (rel_freq_series[i - 1, 2]) / i
    rel_freq_series[i, 1] = (i - 1) * (rel_freq_series[i - 1, 1]) / i
    rel_freq_series[i, 4] = (i - 1) * (rel_freq_series[i - 1, 4]) / i
    rel_freq_series[i, 5] = (i - 1) * (rel_freq_series[i - 1, 5]) / i
  } else if(freq_balls[i] == 3){
    rel_freq_series[i, 4] = (1 + (i - 1) * (rel_freq_series[i - 1, 4])) / i
    rel_freq_series[i, 2] = (i - 1) * (rel_freq_series[i - 1, 2]) / i
    rel_freq_series[i, 3] = (i - 1) * (rel_freq_series[i - 1, 3]) / i
    rel_freq_series[i, 1] = (i - 1) * (rel_freq_series[i - 1, 1]) / i
    rel_freq_series[i, 5] = (i - 1) * (rel_freq_series[i - 1, 5]) / i
  } else{
    rel_freq_series[i, 5] = (1 + (i - 1) * (rel_freq_series[i - 1, 5])) / i
    rel_freq_series[i, 2] = (i - 1) * (rel_freq_series[i - 1, 2]) / i
    rel_freq_series[i, 3] = (i - 1) * (rel_freq_series[i - 1, 3]) / i
    rel_freq_series[i, 4] = (i - 1) * (rel_freq_series[i - 1, 4]) / i
    rel_freq_series[i, 1] = (i - 1) * (rel_freq_series[i - 1, 1]) / i
  }
}
a = seq(1, 1000, 1)
plot(x = a, y = rel_freq_series[, 1], col = "red", xlab = "freqs", ylab = "reps", type = "l", main = "Relative frequencies of number of blue balls", ylim = c(0, 1))
lines(x = a, y = rel_freq_series[, 2], col = "yellow")
lines(x = a, y = rel_freq_series[, 3], col = "green")
lines(x = a, y = rel_freq_series[, 4], col = "blue")
lines(x = a, y = rel_freq_series[, 5], col = "purple")
legend("topright", legend = c(0, 1, 2, 3, 4), fill = c("red", "yellow", "green", "blue", "purple"))
```






















